### ISSUE TITLE
수정사안

### ISSUE THREAD

**Issue by jhj9109** [HELLO-SHELL/HELLO-SHELL#98]
# 1. heredoc ctrl + d에 반응하지 않는이유
https://github.com/HELLO-SHELL/HELLO-SHELL/blob/226dc228e5f817958bb03f5ae0bc3ac6155d46b5/src/executor/heredoc.c#L28-L38

<img width="1861" alt="image" src="https://user-images.githubusercontent.com/36416495/187436762-dc90df03-7fcc-4be3-abf6-5bd3e453f1c8.png">

## 1.1 문제 발단 요인
ctrl + d 입력시 line에  NULL이 들어감. 이때 while문의 조건을 만족하여, while문 내 코드가 실행되고,
line이 NULL이면 터지게 되는 부분이 존재하고(아마도) 그로 인해 코드가 정상 실행 되지 않음

## 1.2 문제 해결 방법
따라서 while 조건문에 line을 추가하여, line이 NULL일때 반복문내로 들어가지 않도록 하면, 정상적으로 코드가 실행됨을 확인

## 1.3 기타 코드 수정
추가적으로 line에 NULL이 들어가는 상황에서 free(line)이 문제를 발생하지 않아 의아했는데,
검색해보니 free(NULL)은 no-op, 동작하지 않는 코드로서, 문제를 발생시키지 않음
우리가 if(line) free(line) 코드를 썻던것은, 호환성에 따라 free(NULL)이 에러를 발생시키기도 하기 때문인듯함
코드 길이가 남으므로 if(line) free(line)으로 바꾸는 것이 바람직해보임
또한, 함수가 끝나는 부분에서 line = NULL;은 사실 아무 역할을 하지 않아, 삭제해도 됨 (line은 함수내에서 선언된 지역변수)

## 1.4 기타사안
ctrl+d 에 의해 line = NULL일때, 줄바꿈이 되지 않아 (사용자 입력시 엔터가 꼭 들어와서 줄바꿈이 일어난다)
보기 더러워보이는데, bash 체크결과 원래 더럽게 출력되는게 맞아서, 안심해도 됨
줄바꿈을 통해 깨끗하게 보이고 싶으면 if(line) free (line) else ft_putstr_fd("\n", STDOUT_FILENO);를 하면 되겠다

# 2. heredoc 파일명 오류나는 까닭
https://github.com/HELLO-SHELL/HELLO-SHELL/blob/96da498257be1a37fcdfa005fc3e5537f9dd41f6/src/executor/heredoc.c#L67-L87
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/36416495/187441037-72aea069-8031-40e5-86b8-b999ef0157c2.png">

## 2.1 문제 발단 요인
사용되는 변수를 꼭 초기화 하라고 했건만 하지 않아서.

## 2.2 문제 해결 방법
적절한 장소에서 해당 히어독 변수를 초기화해준다.
히어독 관련 파일을 생성하기 위한 함수 초입에 설정해주니 잘 되는 듯 하다.
(원래는 readline하는 while문과 heredoc_promt 시그널 함수에 넣어주었었으나, 이곳에만 설정해주어도 될듯하다)

# 3. 시그널 작동시 last_status 할당하지 않는 이슈
https://github.com/HELLO-SHELL/HELLO-SHELL/blob/226dc228e5f817958bb03f5ae0bc3ac6155d46b5/src/utils/signal.c#L15-L29
<img width="1391" alt="image" src="https://user-images.githubusercontent.com/36416495/187446016-0f380b80-57af-491e-9699-66be3b11bd0c.png">
<img width="1325" alt="image" src="https://user-images.githubusercontent.com/36416495/187446062-aeb1805e-abe8-45dd-8fdc-97d5eb0f38c4.png">
<img width="842" alt="image" src="https://user-images.githubusercontent.com/36416495/187446575-af138043-55ff-4bb6-9ea1-2a31ec0372ac.png">

## 3.1 문제 발단
heredoc중 ctrl + c를 하거나, readline에 의해 입력받는 과정에서 ctrl +c 를 하면 last_status가 1이 되는 것을 확인 할 수 있음.
그런데 시그널함수에는 그러한 코드가 부재

## 3.2 해결방법
각 시그널 함수에 last_status를 1로 할당하는 코드 추가
(heredoc의 경우, 동작하는 곳이 서브쉘이므로 exit으로 상태코드를 전달하고 그를 활용하는 것이 필수였음)

**Comment by YeonSeong-Lee** [comment]
thanks a lot.
